# Project

In [622]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import RobustScaler
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression   
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay, precision_score, recall_score   # to measure precision
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

In [623]:
df = pd.read_csv("credit_risk_dataset.csv")

In [624]:
df.head(5)

,Age,Income,Loan_Amount,Credit_Score,Employment_Years,Education_Level,Housing_Status,Default
0,59,52154.0,11276,823,15,Bachelors,Own,0
1,49,116646.0,43663,315,5,PhD,Own,0
2,35,61157.0,18994,428,8,Masters,Own,1
3,63,52154.0,28499,408,26,Bachelors,Rent,0
4,28,148876.0,28040,832,3,Masters,Own,1

In [625]:
df["Education_Level"].unique()

array(['Bachelors', 'PhD', 'Masters', 'High School'], dtype=object)

In [626]:
order = {'Bachelors': 1, 'PhD': 3, 'Masters': 2, 'High School': 0}

In [627]:
df["Education_Level"] = df["Education_Level"].map(order)

In [628]:
df.head(5)

,Age,Income,Loan_Amount,Credit_Score,Employment_Years,Education_Level,Housing_Status,Default
0,59,52154.0,11276,823,15,1,Own,0
1,49,116646.0,43663,315,5,3,Own,0
2,35,61157.0,18994,428,8,2,Own,1
3,63,52154.0,28499,408,26,1,Rent,0
4,28,148876.0,28040,832,3,2,Own,1

In [629]:
df["Housing_Status"].unique()

array(['Own', 'Rent', 'Mortgage'], dtype=object)

In [630]:
OneHot = OneHotEncoder(drop = None, sparse_output = False)
HousingOneHotEncoded = OneHot.fit_transform(df[["Housing_Status"]])
HousingOneHotEncodedDf = pd.DataFrame(HousingOneHotEncoded, columns = OneHot.get_feature_names_out(["Housing_Status"]), index = df.index)
df = pd.concat([df, HousingOneHotEncodedDf], axis = 1)
df = df.drop(columns = ["Housing_Status"])

In [631]:
df.isnull().sum()

Age                         0
Income                     15
Loan_Amount                 0
Credit_Score                0
Employment_Years            0
Education_Level             0
Default                     0
Housing_Status_Mortgage     0
Housing_Status_Own          0
Housing_Status_Rent         0
dtype: int64

In [632]:
df["Income"] = df["Income"].fillna(df["Income"].mean())

In [633]:
y = df["Default"]
x = df.drop(columns = ["Default"])

In [634]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 12)

In [635]:
model = LogisticRegression(max_iter = 1000)
model.fit(x_train, y_train)

LogisticRegression(max_iter=1000)

In [636]:
y_pred = model.predict(x_test)

In [637]:
model.score(x_test, y_test)

0.855

In [638]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[171,   0],
       [ 29,   0]], dtype=int64)

In [639]:
df["Default"].value_counts()

Default
0    862
1    138
Name: count, dtype: int64

In [640]:
recall_score(y_test, y_pred)

0.0

In [641]:
precision_score(y_test, y_pred)

C:\Users\DHANANJAY\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

0.0

In [642]:
RB = RobustScaler()

In [643]:
df.keys()

Index(['Age', 'Income', 'Loan_Amount', 'Credit_Score', 'Employment_Years',
       'Education_Level', 'Default', 'Housing_Status_Mortgage',
       'Housing_Status_Own', 'Housing_Status_Rent'],
      dtype='object')

In [644]:
dfAfterEDA = pd.DataFrame(RB.fit_transform(df), columns = ['Age', 'Income', 'Loan_Amount', 'Credit_Score', 'Employment_Years',
       'Education_Level', 'Default', 'Housing_Status_Mortgage',
       'Housing_Status_Own', 'Housing_Status_Rent'])

In [645]:
dfAfterEDA

,Age,Income,Loan_Amount,Credit_Score,Employment_Years,Education_Level,Default,Housing_Status_Mortgage,Housing_Status_Own,Housing_Status_Rent
0,0.761905,-0.466725,-0.776932,0.863026,0.000000,-0.5,0.0,0.0,1.0,0.0
1,0.285714,0.533275,0.685367,-0.956132,-0.666667,0.5,0.0,0.0,1.0,0.0
2,-0.380952,-0.327127,-0.428459,-0.551477,-0.466667,0.0,1.0,0.0,1.0,0.0
3,0.952381,-0.466725,0.000700,-0.623098,0.733333,-0.5,0.0,0.0,0.0,1.0
4,-0.714286,1.033027,-0.020024,0.895255,-0.800000,0.0,1.0,0.0,1.0,0.0
5,-0.095238,0.081436,0.895634,-0.050134,0.733333,0.5,0.0,0.0,1.0,0.0
6,0.761905,0.391257,-0.294586,-0.433303,0.800000,0.0,0.0,0.0,1.0,0.0
7,-0.190476,-0.508095,-0.784924,-0.082363,-0.933333,0.5,1.0,0.0,1.0,0.0
8,0.000000,-0.902996,0.848090,-0.648165,0.866667,-1.0,0.0,0.0,1.0,0.0
9,-0.571429,-0.282609,-0.176427,0.798568,-0.800000,0.0,1.0,0.0,1.0,0.0
10,-0.571429,-0.929077,0.562692,-0.128917,-1.000000,0.0,1.0,0.0,0.0,1.0
11,0.047619,1.035539,-0.784157,0.909579,0.200000,-1.0,0.0,0.0,1.0,0.0
12,0.619048,1.035539,-0.357617,-0.544315,0.666667,0.0,0.0,0.0,1.0,0.0
13,0.809524,-0.465004,0.149201,0.250671,0.600000,-1.0,0.0,1.0,0.0,0.0
14,0.047619,-0.465004,0.155522,-0.311549,-0.400000,-0.5,0.0,0.0,0.0,1.0
15,-0.952381,0.068256,0.580301,0.354521,0.333333,0.5,0.0,0.0,0.0,1.0
16,-0.047619,-0.109689,-0.615699,-0.200537,-0.066667,-1.0,0.0,0.0,0.0,1.0
17,-1.000000,-0.282609,0.120620,0.691137,0.733333,0.0,0.0,0.0,0.0,1.0
18,0.047619,-0.327127,-0.422092,0.694718,0.400000,-1.0,0.0,0.0,1.0,0.0
19,1.000000,-0.818831,-0.257789,-0.064458,0.200000,0.0,1.0,0.0,1.0,0.0
20,0.333333,0.535802,-0.981646,0.318711,0.000000,-0.5,0.0,1.0,0.0,0.0
21,0.714286,-0.585112,-0.233633,0.726947,0.333333,-1.0,0.0,1.0,0.0,0.0
22,-1.000000,-0.285028,-1.032351,0.540734,0.733333,-0.5,0.0,0.0,0.0,1.0
23,-0.095238,0.775227,-0.263026,-0.257833,0.533333,0.5,0.0,1.0,0.0,0.0
24,0.476190,-0.113767,0.506750,0.336616,0.400000,0.0,0.0,1.0,0.0,0.0
25,-0.523810,0.533275,-0.142067,0.401074,-0.800000,0.0,0.0,0.0,0.0,1.0
26,-0.047619,-0.168983,-0.337841,0.598030,-0.933333,-0.5,1.0,0.0,0.0,1.0
27,1.000000,1.033027,-1.016593,0.290063,0.933333,0.5,0.0,1.0,0.0,0.0
28,0.095238,0.068256,0.108746,0.623098,0.600000,-1.0,0.0,0.0,1.0,0.0
29,0.190476,0.149677,0.096420,-0.204118,-0.200000,-1.0,0.0,1.0,0.0,0.0
30,0.904762,-0.109689,-1.047612,-0.544315,0.800000,0.0,1.0,1.0,0.0,0.0
31,0.238095,0.391257,0.177736,0.691137,-1.000000,-0.5,0.0,0.0,1.0,0.0
32,-0.333333,0.068256,-0.366783,-0.021486,0.066667,-0.5,0.0,0.0,1.0,0.0
33,-0.380952,-0.084275,0.701937,-0.454790,-0.200000,-1.0,0.0,0.0,0.0,1.0
34,1.000000,-0.285028,-1.012529,-0.232766,-0.800000,0.5,0.0,0.0,0.0,1.0
35,-0.952381,-0.044580,-0.126716,-0.333035,-0.600000,0.5,0.0,1.0,0.0,0.0
36,0.666667,0.549928,-0.576102,0.479857,0.066667,-1.0,0.0,0.0,1.0,0.0
37,-0.761905,0.085669,0.222165,0.941808,-0.466667,-1.0,1.0,0.0,0.0,1.0
38,-0.095238,1.033027,0.652993,-0.866607,-0.800000,-0.5,0.0,1.0,0.0,0.0
39,-0.666667,-0.285028,0.734355,0.085944,0.200000,0.5,0.0,0.0,1.0,0.0
40,0.761905,-0.109689,0.287723,0.196956,-1.000000,-1.0,0.0,1.0,0.0,0.0
41,-0.238095,0.391257,-0.644912,0.111012,-0.400000,-1.0,0.0,0.0,0.0,1.0
42,-0.904762,-0.597656,0.474693,-0.744852,-0.800000,0.0,0.0,0.0,0.0,1.0
43,0.095238,-0.465004,0.096058,-0.014324,-0.466667,-1.0,0.0,0.0,1.0,0.0
44,-0.428571,0.149491,0.801494,-0.383169,-0.200000,-1.0,0.0,1.0,0.0,0.0
45,-0.666667,0.081436,0.522553,-0.035810,-0.133333,0.5,0.0,0.0,1.0,0.0
46,0.142857,-0.327127,-1.004357,0.021486,-0.400000,-0.5,0.0,0.0,0.0,1.0
47,-1.000000,0.630496,0.661662,-0.039391,-0.666667,0.5,0.0,0.0,0.0,1.0
48,-0.142857,0.533275,-1.054655,-0.777081,0.000000,-0.5,0.0,1.0,0.0,0.0
49,0.238095,0.984292,0.016864,0.716204,-0.666667,0.0,0.0,1.0,0.0,0.0
50,-0.761905,0.033817,-0.365067,-0.125336,0.066667,-1.0,0.0,1.0,0.0,0.0
51,1.000000,0.034577,-0.760588,-0.454790,-0.400000,0.0,1.0,0.0,1.0,0.0
52,-0.714286,-0.929077,-0.763658,-0.845121,0.133333,-0.5,0.0,1.0,0.0,0.0
53,0.571429,0.323574,-0.913604,0.612355,0.733333,0.5,0.0,1.0,0.0,0.0
54,-0.428571,1.035539,-0.648975,-0.293644,0.400000,0.5,1.0,0.0,0.0,1.0
55,-0.285714,-0.466725,0.762123,-0.569382,0.133333,0.0,1.0,0.0,0.0,1.0
56,0.619048,0.289275,-0.446022,-1.009848,-0.866667,-0.5,0.0,1.0,0.0,0.0
57,0.809524,-0.285028,-0.513297,-0.329454,0.266667,0.0,0.0,1.0,0.0,0.0
58,-0.904762,-0.248977,0.703382,0.834378,0.733333,0.0,0.0,0.0,0.0,1.0
59,-1.000000,0.565480,-0.025849,0.569382,0.333333,-1.0,0.0,1.0,0.0,0.0
60,-0.809524,0.535802,0.679136,-0.501343,0.600000,0.0,0.0,0.0,1.0,0.0
61,0.904762,-0.168983,0.409631,-0.329454,0.800000,-1.0,0.0,0.0,1.0,0.0
62,-0.904762,0.000000,-0.491625,0.895255,-0.066667,-1.0,0.0,0.0,1.0,0.0
63,0.285714,0.149677,-0.971397,-0.200537,-0.066667,0.5,0.0,1.0,0.0,0.0
64,-0.238095,0.630496,0.915184,0.107431,-0.800000,-1.0,0.0,0.0,0.0,1.0
65,0.142857,-0.951002,-0.280319,0.068039,0.866667,-1.0,0.0,1.0,0.0,0.0
66,1.000000,0.068256,-0.858475,0.633841,0.733333,0.5,0.0,1.0,0.0,0.0
67,0.523810,0.149677,-0.598632,0.422560,-0.466667,0.0,0.0,0.0,0.0,1.0
68,-0.619048,-0.465004,0.850664,0.393912,0.733333,-0.5,0.0,0.0,0.0,1.0
69,0.619048,-0.168983,0.834861,-0.272158,0.666667,-0.5,0.0,0.0,0.0,1.0
70,-0.428571,0.000000,0.870304,-0.261415,0.200000,-0.5,0.0,0.0,1.0,0.0
71,0.380952,1.035539,-0.012981,-0.601611,0.533333,0.0,1.0,1.0,0.0,0.0
72,-0.380952,-0.285028,0.758692,-0.114593,0.800000,-1.0,0.0,0.0,0.0,1.0
73,-0.714286,0.902065,-0.443133,-0.229185,0.066667,-0.5,0.0,1.0,0.0,0.0
74,-0.428571,-0.951002,0.627438,0.444047,-0.333333,0.0,1.0,0.0,1.0,0.0
75,0.000000,1.033027,0.655703,0.572963,0.600000,-1.0,0.0,0.0,1.0,0.0
76,0.809524,0.323574,-0.356985,0.254252,-0.466667,0.5,0.0,0.0,0.0,1.0
77,-0.095238,0.323574,-0.045625,0.956132,-0.400000,-0.5,1.0,0.0,0.0,1.0
78,-0.333333,-0.585112,0.232143,-0.504924,0.133333,-1.0,0.0,1.0,0.0,0.0
79,-0.238095,0.068256,-0.360281,0.780662,0.266667,-0.5,0.0,0.0,0.0,1.0
80,0.047619,-0.248977,0.027339,0.945389,-0.200000,-0.5,0.0,1.0,0.0,0.0
81,0.142857,-0.047340,0.587118,0.927484,-0.533333,-0.5,0.0,0.0,0.0,1.0
82,0.095238,0.549928,-1.046663,0.802149,-0.600000,-1.0,0.0,1.0,0.0,0.0
83,0.857143,0.068256,0.360281,-0.007162,0.066667,0.0,0.0,1.0,0.0,0.0
84,0.285714,0.535802,0.967514,0.504924,0.333333,-1.0,0.0,1.0,0.0,0.0
85,-0.380952,0.775227,0.260768,-0.046553,0.466667,-0.5,0.0,1.0,0.0,0.0
86,-1.047619,-0.902996,0.873194,-0.461952,-0.066667,-1.0,0.0,0.0,1.0,0.0
87,0.095238,0.472678,0.619672,-0.716204,0.266667,0.5,0.0,1.0,0.0,0.0
88,-0.761905,-0.044580,0.323980,0.512086,-0.066667,0.0,0.0,0.0,0.0,1.0
89,-0.666667,-0.282609,0.557906,-0.028648,-1.000000,-1.0,0.0,0.0,1.0,0.0
90,0.047619,-0.670239,0.379560,0.003581,0.600000,0.5,0.0,0.0,1.0,0.0
91,-1.047619,-0.282609,-0.446338,-0.393912,-0.133333,0.0,0.0,1.0,0.0,0.0
92,1.000000,-0.881443,-0.179497,0.157565,-0.733333,0.5,0.0,0.0,1.0,0.0
93,-0.714286,-0.109689,0.848993,-0.787825,-0.333333,0.0,0.0,1.0,0.0,0.0
94,0.047619,-0.597656,-0.456181,-0.752014,0.000000,-1.0,1.0,0.0,0.0,1.0
95,-0.571429,1.035539,0.158050,0.329454,-0.933333,0.5,0.0,1.0,0.0,0.0
96,-0.285714,-0.798007,0.954917,0.805730,-0.533333,-0.5,0.0,0.0,1.0,0.0
97,-0.714286,0.549928,-0.693449,0.411817,-0.333333,0.5,0.0,0.0,0.0,1.0
98,0.571429,0.472678,0.567794,-0.583706,0.866667,0.0,1.0,1.0,0.0,0.0
99,0.571429,-0.113767,-0.878206,0.551477,0.133333,-1.0,0.0,0.0,0.0,1.0
100,0.476190,-0.798007,0.649697,0.651746,-0.866667,0.0,0.0,0.0,0.0,1.0
101,-0.857143,0.085669,-0.288807,0.010743,0.933333,0.5,0.0,0.0,1.0,0.0
102,0.904762,0.033817,0.786414,-0.064458,0.666667,0.5,0.0,0.0,0.0,1.0
103,0.761905,-0.466725,-0.802759,0.132498,-1.000000,-0.5,0.0,0.0,1.0,0.0
104,0.857143,-0.109689,-0.705955,0.333035,-0.333333,-1.0,0.0,0.0,0.0,1.0
105,0.238095,0.565480,-0.085403,-0.694718,0.000000,-1.0,1.0,1.0,0.0,0.0
106,-0.761905,0.068256,-0.747675,-0.286482,0.133333,0.5,0.0,0.0,0.0,1.0
107,-0.666667,0.034577,0.168164,0.182632,0.933333,-1.0,0.0,1.0,0.0,0.0
108,-0.714286,-0.335283,-0.174711,-0.218442,0.000000,-0.5,1.0,1.0,0.0,0.0
109,-0.523810,-0.951002,-1.038265,-0.866607,0.466667,0.0,0.0,0.0,0.0,1.0
110,0.523810,0.033817,0.740405,-0.769919,-0.400000,-1.0,0.0,1.0,0.0,0.0
111,0.476190,0.472678,0.110145,0.827216,0.133333,0.5,0.0,0.0,0.0,1.0
112,0.000000,-0.881443,0.562466,-0.558639,-0.666667,0.0,0.0,0.0,0.0,1.0
113,0.047619,-0.818831,0.256524,-0.100269,0.200000,0.0,0.0,1.0,0.0,0.0
114,0.666667,-0.248977,-0.985033,-0.956132,-0.800000,-0.5,0.0,1.0,0.0,0.0
115,0.571429,0.033817,0.123239,0.694718,0.733333,0.5,0.0,0.0,1.0,0.0
116,1.000000,-0.818831,-0.874548,-0.791406,-0.200000,-1.0,0.0,1.0,0.0,0.0
117,0.809524,0.565480,0.579623,0.533572,0.533333,0.5,0.0,0.0,1.0,0.0
118,-0.047619,0.034577,-0.709884,-0.053715,-0.133333,0.0,0.0,1.0,0.0,0.0
119,0.190476,-0.285028,0.344614,-0.888093,-0.866667,0.5,0.0,0.0,0.0,1.0
120,0.571429,0.033817,0.464353,0.755595,-0.400000,-1.0,0.0,1.0,0.0,0.0
121,-1.047619,0.472678,0.087705,0.666070,-0.666667,-1.0,0.0,0.0,0.0,1.0
122,0.571429,0.000000,-0.257879,0.150403,-1.000000,-0.5,0.0,0.0,0.0,1.0
123,0.666667,0.642296,0.665275,0.075201,0.466667,-1.0,1.0,0.0,0.0,1.0
124,-0.428571,-0.084275,-0.892699,-0.025067,0.533333,-1.0,0.0,0.0,1.0,0.0
125,-0.952381,0.319667,-0.998578,-0.293644,0.733333,0.5,0.0,1.0,0.0,0.0
126,-1.047619,-0.168983,0.788943,0.580125,-0.133333,0.5,0.0,0.0,0.0,1.0
127,-0.857143,1.035539,0.826147,0.146822,-0.533333,0.0,0.0,0.0,0.0,1.0
128,0.142857,-0.576832,0.122652,-0.888093,0.200000,-0.5,0.0,0.0,1.0,0.0
129,-0.428571,0.642296,-0.892067,0.712623,-0.133333,0.5,0.0,1.0,0.0,0.0
130,0.761905,0.319667,0.005982,0.705461,-0.400000,-1.0,0.0,1.0,0.0,0.0
131,0.190476,-0.466725,0.191417,-0.780662,0.066667,0.0,0.0,0.0,1.0,0.0
132,-0.666667,0.033817,0.636197,-0.984781,-0.466667,0.5,0.0,0.0,1.0,0.0
133,-0.380952,-0.508095,0.518083,0.064458,0.866667,-0.5,0.0,1.0,0.0,0.0
134,-0.380952,-0.466725,-0.649065,0.214861,-0.666667,-0.5,0.0,0.0,1.0,0.0
135,0.142857,0.319667,-0.510452,0.529991,-0.333333,0.0,0.0,1.0,0.0,0.0
136,0.904762,0.140637,0.549011,0.504924,0.600000,0.0,0.0,1.0,0.0,0.0
137,-0.476190,-0.285028,0.354005,0.175470,-0.600000,0.0,0.0,0.0,0.0,1.0
138,0.428571,-0.576832,0.671686,0.555058,0.066667,0.0,0.0,0.0,0.0,1.0
139,0.761905,-0.044580,-0.255531,-0.390331,0.800000,0.0,0.0,1.0,0.0,0.0
140,0.428571,0.000000,-0.657238,0.873769,0.800000,-1.0,0.0,1.0,0.0,0.0
141,-0.904762,0.289275,0.210425,-0.920322,-1.000000,-1.0,0.0,1.0,0.0,0.0
142,0.333333,1.035539,0.339828,0.440466,0.400000,0.5,0.0,1.0,0.0,0.0
143,0.666667,1.033027,-0.046979,-0.182632,-0.733333,-0.5,0.0,1.0,0.0,0.0
144,0.000000,-0.335283,-0.408457,0.895255,-0.466667,-1.0,0.0,1.0,0.0,0.0
145,0.761905,-0.902996,0.939791,0.956132,0.133333,-1.0,1.0,0.0,1.0,0.0
146,-0.380952,0.034577,0.735710,0.794987,0.533333,-1.0,0.0,1.0,0.0,0.0
147,0.952381,0.033817,-0.554294,-0.372426,0.733333,0.5,0.0,0.0,1.0,0.0
148,0.285714,-0.335283,0.092717,-0.540734,0.333333,0.0,0.0,0.0,1.0,0.0
149,0.619048,0.319667,0.554158,0.615936,-0.933333,0.5,0.0,1.0,0.0,0.0
150,-0.476190,0.775227,-0.516683,0.232766,0.866667,-0.5,1.0,1.0,0.0,0.0
151,0.428571,1.035539,0.835403,0.920322,0.666667,-0.5,0.0,0.0,1.0,0.0
152,-0.761905,0.081436,-0.039349,0.440466,-0.333333,-0.5,0.0,0.0,1.0,0.0
153,-0.047619,0.000000,0.223835,-0.741271,0.733333,-0.5,0.0,1.0,0.0,0.0
154,0.238095,0.533275,-0.768128,0.748433,0.800000,-1.0,0.0,1.0,0.0,0.0
155,-1.000000,-0.466725,0.548469,-0.318711,-0.666667,-1.0,0.0,0.0,1.0,0.0
156,0.904762,0.841949,0.902000,-0.433303,0.666667,0.5,0.0,0.0,1.0,0.0
157,-0.809524,-0.790052,0.137236,0.229185,-0.533333,0.0,0.0,0.0,1.0,0.0
158,0.238095,0.642296,0.355088,0.279320,-0.800000,-0.5,0.0,0.0,0.0,1.0
159,0.238095,-0.585112,-1.007156,-0.701880,0.133333,0.5,0.0,0.0,1.0,0.0
160,1.000000,-0.585112,-0.845381,-0.075201,0.800000,-1.0,1.0,0.0,0.0,1.0
161,1.000000,-0.576832,0.419699,-0.247090,-0.333333,-1.0,0.0,1.0,0.0,0.0
162,-0.142857,0.149677,-0.083416,-0.075201,-0.733333,0.0,0.0,1.0,0.0,0.0
163,0.333333,-0.670239,-0.321948,0.000000,-0.066667,0.0,0.0,0.0,1.0,0.0
164,-0.571429,0.085669,-0.538536,0.658908,0.800000,0.0,0.0,1.0,0.0,0.0
165,0.238095,-0.168983,0.185773,0.347359,0.133333,0.5,0.0,1.0,0.0,0.0
166,0.095238,0.034577,-0.538220,0.282901,-0.933333,-1.0,0.0,1.0,0.0,0.0
167,0.761905,0.642296,0.916855,0.594449,0.400000,-1.0,0.0,1.0,0.0,0.0
168,0.476190,-0.335283,-0.688527,0.565801,-0.333333,0.0,1.0,0.0,0.0,1.0
169,-1.047619,0.472678,0.091904,-0.680394,0.666667,-0.5,0.0,0.0,0.0,1.0
170,0.190476,-0.466725,0.157238,0.504924,0.600000,0.0,0.0,0.0,1.0,0.0
171,-0.476190,0.533275,-0.330075,-0.504924,-0.200000,0.5,0.0,0.0,1.0,0.0
172,0.857143,0.000000,0.158186,0.028648,-0.800000,0.0,0.0,0.0,1.0,0.0
173,-0.952381,-0.790052,-0.465302,0.533572,0.400000,0.0,0.0,1.0,0.0,0.0
174,0.761905,-0.798007,0.715843,-0.837959,-0.600000,0.5,0.0,1.0,0.0,0.0
175,-0.809524,-0.168983,0.050230,0.068039,0.866667,0.0,0.0,0.0,0.0,1.0
176,-0.714286,0.533275,0.437534,-0.333035,-0.333333,-1.0,1.0,0.0,0.0,1.0
177,0.190476,1.033027,0.834861,-0.526410,0.400000,-0.5,0.0,0.0,1.0,0.0
178,-0.666667,0.630496,-0.860236,0.433303,0.533333,0.0,0.0,0.0,0.0,1.0
179,0.666667,-0.790052,0.193268,0.207699,-0.800000,0.5,0.0,0.0,0.0,1.0
180,0.476190,1.035539,-0.083822,0.125336,0.800000,-0.5,0.0,0.0,0.0,1.0
181,0.904762,0.085669,0.714579,0.286482,-0.066667,0.5,0.0,0.0,0.0,1.0
182,1.000000,0.034577,-0.658186,0.354521,-1.000000,-0.5,0.0,0.0,0.0,1.0
183,0.047619,1.033027,0.606398,-0.179051,0.466667,-0.5,0.0,0.0,1.0,0.0
184,-0.380952,0.533275,0.963089,0.218442,-0.866667,0.0,0.0,0.0,1.0,0.0
185,0.428571,-0.670239,-0.469907,0.952551,-0.133333,-1.0,0.0,0.0,0.0,1.0
186,0.428571,-0.047340,0.639629,0.880931,-0.666667,0.0,0.0,0.0,1.0,0.0
187,0.047619,0.642296,-0.788852,-0.358102,0.133333,0.5,0.0,1.0,0.0,0.0
188,0.857143,-0.798007,-0.737426,-0.866607,0.600000,0.5,0.0,0.0,0.0,1.0
189,-0.523810,0.289275,0.213450,0.408236,-1.000000,-0.5,0.0,1.0,0.0,0.0
190,0.761905,0.642296,0.164055,0.755595,-0.666667,-0.5,0.0,0.0,1.0,0.0
191,-1.000000,0.149677,0.582197,0.179051,-0.666667,-1.0,0.0,0.0,1.0,0.0
192,-0.952381,-0.109689,0.865473,-0.558639,0.333333,0.0,0.0,1.0,0.0,0.0
193,0.666667,0.140637,-0.749029,-1.009848,0.000000,0.5,0.0,0.0,1.0,0.0
194,-0.285714,0.081436,-0.452253,-0.411817,0.866667,-0.5,0.0,0.0,0.0,1.0
195,-1.000000,0.630496,0.339828,-0.945389,-0.733333,-1.0,0.0,1.0,0.0,0.0
196,-1.000000,-0.951002,0.864977,0.175470,0.066667,0.5,0.0,0.0,0.0,1.0
197,0.238095,0.289275,-0.505441,0.619517,-0.400000,-0.5,0.0,1.0,0.0,0.0
198,0.000000,-0.929077,0.970404,-0.623098,0.800000,0.5,0.0,0.0,1.0,0.0
199,0.666667,0.149491,0.908096,-0.053715,0.333333,-1.0,0.0,1.0,0.0,0.0
200,0.428571,-0.044580,-0.014110,0.580125,0.133333,-1.0,0.0,1.0,0.0,0.0
201,0.476190,0.472678,0.515690,-0.153984,-0.600000,0.5,0.0,0.0,0.0,1.0
202,-1.047619,-0.585112,-0.119853,0.064458,-0.866667,0.0,0.0,0.0,1.0,0.0
203,-0.190476,0.472678,0.477267,-0.644584,-0.200000,0.5,0.0,0.0,0.0,1.0
204,-1.000000,0.085669,0.932612,-0.118174,-0.066667,-0.5,1.0,0.0,1.0,0.0
205,1.000000,-0.168983,0.282215,0.608774,0.266667,0.0,0.0,0.0,0.0,1.0
206,0.142857,-0.951002,-0.741895,0.848702,0.200000,-0.5,0.0,1.0,0.0,0.0
207,0.428571,-0.576832,-0.895318,-0.465533,-0.866667,0.5,0.0,0.0,0.0,1.0
208,-0.809524,0.149491,0.000113,-0.390331,-0.800000,0.0,0.0,0.0,1.0,0.0
209,0.428571,-0.576832,-0.214037,0.214861,-0.733333,-0.5,0.0,0.0,1.0,0.0
210,-0.904762,-0.465004,0.045399,0.529991,-1.000000,0.5,0.0,1.0,0.0,0.0
211,-0.571429,-0.466725,-0.670377,0.146822,-0.800000,0.5,0.0,0.0,1.0,0.0
212,-0.285714,-0.044580,-0.769483,0.490600,-0.266667,0.0,0.0,0.0,0.0,1.0
213,0.714286,-0.902996,0.050908,0.723366,0.800000,0.5,0.0,1.0,0.0,0.0
214,0.047619,0.000000,0.855675,0.461952,0.733333,-1.0,0.0,0.0,1.0,0.0
215,-0.857143,1.033027,-0.511762,-0.712623,0.533333,-0.5,0.0,0.0,1.0,0.0
216,0.523810,-0.327127,0.500384,-0.608774,-0.400000,-0.5,0.0,0.0,0.0,1.0
217,-0.809524,-0.818831,0.852650,0.175470,0.466667,0.5,0.0,0.0,0.0,1.0
218,-0.047619,0.535802,-0.081655,0.340197,0.600000,0.5,1.0,1.0,0.0,0.0
219,-0.571429,0.984292,-0.812195,-0.866607,0.333333,-1.0,1.0,0.0,1.0,0.0
220,-0.333333,-0.902996,0.866196,-0.637422,0.866667,0.0,0.0,0.0,0.0,1.0
221,0.476190,-0.790052,-0.442952,-0.290063,0.666667,0.5,0.0,1.0,0.0,0.0
222,-0.666667,-0.168983,-0.557770,0.598030,0.266667,0.5,1.0,0.0,1.0,0.0
223,-0.809524,0.391257,-0.036820,-0.060877,0.533333,0.5,0.0,0.0,1.0,0.0
224,-0.333333,-0.818831,-0.373013,-0.261415,0.600000,0.5,0.0,1.0,0.0,0.0
225,0.285714,-0.327127,0.008375,-0.590868,-0.200000,-0.5,1.0,1.0,0.0,0.0
226,-0.952381,0.630496,0.477899,0.336616,0.466667,0.5,0.0,0.0,0.0,1.0
227,-0.142857,0.775227,-0.010407,0.920322,-0.133333,-0.5,0.0,0.0,1.0,0.0
228,0.619048,0.319667,-0.634301,-0.712623,0.466667,0.5,0.0,0.0,1.0,0.0
229,-0.190476,0.323574,0.228847,0.612355,-0.733333,0.0,0.0,0.0,1.0,0.0
230,0.142857,-0.670239,0.627619,0.827216,-0.800000,-1.0,0.0,1.0,0.0,0.0
231,-0.952381,-0.597656,-0.320142,0.372426,-0.133333,0.0,0.0,0.0,0.0,1.0
232,-0.190476,-0.047340,-0.580933,0.239928,-0.400000,0.5,0.0,0.0,1.0,0.0
233,-0.142857,0.565480,0.678910,0.046553,0.066667,0.5,0.0,1.0,0.0,0.0
234,0.428571,-0.597656,-0.615473,-0.089526,-0.400000,0.5,0.0,0.0,1.0,0.0
235,-0.761905,-0.798007,0.357481,-0.723366,0.666667,0.0,0.0,0.0,0.0,1.0
236,0.857143,-0.881443,-0.776075,-0.053715,-0.600000,0.5,0.0,0.0,1.0,0.0
237,0.476190,-0.585112,0.564814,0.487019,0.000000,0.0,1.0,0.0,0.0,1.0
238,0.809524,0.319667,0.478621,-0.171889,-1.000000,-0.5,0.0,0.0,0.0,1.0
239,0.761905,0.149677,0.726544,0.100269,0.066667,-1.0,0.0,0.0,1.0,0.0
240,-0.238095,-0.168983,0.585493,0.264996,0.333333,-1.0,0.0,0.0,1.0,0.0
241,0.809524,0.642296,-0.733994,-0.250671,0.866667,0.0,0.0,0.0,0.0,1.0
242,-1.047619,-0.881443,0.380463,-0.837959,-0.466667,-0.5,0.0,1.0,0.0,0.0
243,-0.571429,-0.335283,0.566981,-0.558639,-0.666667,0.0,0.0,0.0,0.0,1.0
244,0.238095,1.035539,-0.004493,-0.214861,0.200000,-0.5,0.0,0.0,1.0,0.0
245,0.095238,-0.881443,-1.053752,-0.014324,-0.200000,0.5,0.0,0.0,1.0,0.0
246,0.000000,0.289275,0.645408,0.447628,-0.866667,-0.5,0.0,1.0,0.0,0.0
247,0.380952,0.323574,-0.336306,0.794987,-0.600000,-0.5,0.0,0.0,0.0,1.0
248,0.333333,-0.285028,-0.923040,0.039391,0.400000,-0.5,0.0,0.0,0.0,1.0
249,0.904762,-0.902996,0.855088,-0.021486,-0.466667,-1.0,0.0,0.0,0.0,1.0
250,0.571429,-0.508095,0.120846,0.555058,0.400000,-0.5,0.0,0.0,1.0,0.0
251,-0.761905,0.549928,-0.264155,-0.630260,-0.733333,0.5,0.0,0.0,0.0,1.0
252,-0.333333,0.841949,0.264606,0.490600,-0.400000,0.5,1.0,1.0,0.0,0.0
253,0.142857,0.323574,-0.292103,0.522829,0.466667,0.5,0.0,0.0,1.0,0.0
254,-1.000000,0.565480,-0.383217,0.329454,0.066667,-0.5,0.0,0.0,1.0,0.0
255,-1.047619,-0.109689,0.818923,-0.752014,-0.266667,0.0,0.0,0.0,0.0,1.0
256,-0.523810,0.149677,-0.532260,-0.905998,0.466667,0.0,0.0,1.0,0.0,0.0
257,-0.857143,0.081436,-0.931529,-0.340197,0.000000,0.5,0.0,0.0,1.0,0.0
258,0.666667,0.068256,-0.337254,0.290063,-0.866667,-1.0,0.0,0.0,1.0,0.0
259,0.428571,-0.466725,0.160669,0.601611,0.933333,0.0,0.0,0.0,0.0,1.0
260,-0.666667,-0.508095,0.463766,-0.315130,0.600000,-0.5,0.0,0.0,0.0,1.0
261,0.857143,-0.670239,0.763342,-0.454790,0.400000,0.0,0.0,1.0,0.0,0.0
262,0.571429,-0.168983,0.010272,-0.397493,-0.466667,0.5,0.0,0.0,0.0,1.0
263,-0.190476,0.630496,0.119130,-0.866607,0.866667,-1.0,0.0,1.0,0.0,0.0
264,-0.333333,0.535802,-0.646718,-0.787825,-0.066667,0.0,0.0,0.0,1.0,0.0
265,-0.952381,-0.113767,0.168390,-0.931065,-0.733333,0.0,0.0,1.0,0.0,0.0
266,-0.142857,-0.044580,0.719546,0.275739,0.466667,0.5,0.0,1.0,0.0,0.0
267,0.047619,-0.951002,-0.725235,-0.744852,-0.200000,-1.0,0.0,1.0,0.0,0.0
268,0.476190,0.984292,-0.094072,-0.590868,-0.133333,-1.0,0.0,0.0,1.0,0.0
269,0.047619,-0.465004,0.453924,0.347359,0.266667,0.5,1.0,0.0,0.0,1.0
270,-0.571429,-0.248977,-0.259911,0.025067,-0.066667,-0.5,0.0,0.0,1.0,0.0
271,-0.714286,0.775227,-0.863532,0.562220,0.000000,0.0,0.0,0.0,0.0,1.0
272,0.619048,-0.670239,0.225686,-0.988362,0.466667,-0.5,0.0,1.0,0.0,0.0
273,0.714286,-0.881443,0.389809,-0.311549,-0.200000,0.0,0.0,1.0,0.0,0.0
274,0.809524,0.630496,-0.014426,0.494181,0.066667,0.0,0.0,1.0,0.0,0.0
275,-0.142857,0.549928,0.380463,-0.322292,0.466667,-0.5,0.0,1.0,0.0,0.0
276,0.571429,0.775227,0.406922,-0.483438,-0.533333,0.5,0.0,1.0,0.0,0.0

In [646]:
y = dfAfterEDA["Default"]
x = dfAfterEDA.drop(columns = ["Default"])

In [647]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 65, shuffle = True)

In [648]:
modelAfterScaling = LogisticRegression(max_iter = 10000, class_weight = "balanced")
modelAfterScaling.fit(x_train, y_train)

LogisticRegression(class_weight='balanced', max_iter=10000)

In [649]:
y_pred = model.predict(x_test)

In [650]:
model.score(x_test, y_test)

0.865

In [651]:
cmAfterEDA = confusion_matrix(y_test, y_pred)
cmAfterEDA

array([[173,   0],
       [ 27,   0]], dtype=int64)

In [652]:
set(y_pred)

{0}

In [653]:
precision_score(y_test, y_pred)

C:\Users\DHANANJAY\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

0.0